-- Switch context to the master database to manage databases
USE master;
GO

-- Drop DB_BCA if it exists
IF DB_ID('DB_BCA') IS NOT NULL
BEGIN
    ALTER DATABASE [DB_BCA] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [DB_BCA];
END
GO

-- Drop DB_BTP if it exists
IF DB_ID('DB_BTP') IS NOT NULL
BEGIN
    ALTER DATABASE [DB_BTP] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [DB_BTP];
END
GO

-- Create DB_BCA database
CREATE DATABASE [DB_BCA]
COLLATE Vietnamese_CI_AS;
GO

-- Create DB_BTP database
CREATE DATABASE [DB_BTP]
COLLATE Vietnamese_CI_AS;
GO

