version: '3.8'

services:
  postgres-qldcqg:
    build:
      context: . # Chỉ định thư mục chứa Dockerfile
      dockerfile: Dockerfile
    container_name: postgres_qldcqg_container
    environment:
      # Sử dụng biến môi trường để thiết lập user/password superuser ban đầu
      # User này sẽ được dùng bởi script init-db.sh
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # Mặc định là postgres nếu không set ở .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123} # **QUAN TRỌNG: Thay đổi hoặc dùng file .env**
      POSTGRES_DB: postgres # DB mặc định, script init sẽ tạo các DB khác
      # Biến môi trường cho mật khẩu các role khác (nên dùng secrets hoặc .env)
      DB_PASSWORD_ADMIN_BCA: ${DB_PASSWORD_ADMIN_BCA:-SecureMPS_ChangeMe!2025}
      DB_PASSWORD_ADMIN_BTP: ${DB_PASSWORD_ADMIN_BTP:-SecureMOJ_ChangeMe!2025}
      DB_PASSWORD_ADMIN_TT: ${DB_PASSWORD_ADMIN_TT:-SecureCentral_ChangeMe!2025}
      DB_PASSWORD_READER_BCA: ${DB_PASSWORD_READER_BCA:-ReaderMPS_ChangeMe!2025}
      DB_PASSWORD_READER_BTP: ${DB_PASSWORD_READER_BTP:-ReaderMOJ_ChangeMe!2025}
      DB_PASSWORD_READER_TT: ${DB_PASSWORD_READER_TT:-ReaderCentral_ChangeMe!2025}
      DB_PASSWORD_WRITER_BCA: ${DB_PASSWORD_WRITER_BCA:-WriterMPS_ChangeMe!2025}
      DB_PASSWORD_WRITER_BTP: ${DB_PASSWORD_WRITER_BTP:-WriterMOJ_ChangeMe!2025}
      DB_PASSWORD_SYNC_USER: ${DB_PASSWORD_SYNC_USER:-SyncUser_ChangeMe!2025}
    ports:
      - "${DB_PORT:-5432}:5432" # Map port 5432 của container ra port 5432 (hoặc port khác) của máy host
    volumes:
      # Mount volume để lưu trữ dữ liệu PostgreSQL persistent
      - pgdata_qldcqg:/var/lib/postgresql/data
      # Mount các file cấu hình tùy chỉnh vào đúng vị trí trong container
      # Điều này ghi đè lên file cấu hình mặc định sau khi initdb chạy
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    # (Tùy chọn) Cấu hình healthcheck để chờ DB sẵn sàng
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    restart: unless-stopped # Tự khởi động lại container trừ khi bị stop thủ công

volumes:
  pgdata_qldcqg: # Định nghĩa volume để lưu dữ liệu

# (Tùy chọn) Định nghĩa network nếu cần kết nối từ các container khác
# networks:
#   qldcqg_network:
#     driver: bridge

