# Lưu tệp này với tên docker-compose.yaml
version: '3.8' # Phiên bản Docker Compose

services:
  # Service cho DB_BCA (Bộ Công an)
  sql-bca:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_bca
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Duyhung123' # Cân nhắc sử dụng mật khẩu mạnh hơn và khác nhau cho mỗi instance trong môi trường thực tế
      MSSQL_PID: 'Developer'
    ports:
      - "1401:1433" # Map cổng 1401 của host vào cổng 1433 của container sql_bca
    volumes:
      - sql_bca_data:/var/opt/mssql
    networks:
      - citizen_network
    restart: unless-stopped

  # Service cho DB_BTP (Bộ Tư pháp)
  sql-btp:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_btp
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Duyhung123' # Cân nhắc sử dụng mật khẩu mạnh hơn và khác nhau cho mỗi instance
      MSSQL_PID: 'Developer'
    ports:
      - "1402:1433" # Map cổng 1402 của host vào cổng 1433 của container sql_btp
    volumes:
      - sql_btp_data:/var/opt/mssql
    networks:
      - citizen_network
    restart: unless-stopped

  # Service cho DB_Reference (CSDL Tham chiếu Dùng chung)
  sql-reference:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_reference
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Duyhung123' # Cân nhắc sử dụng mật khẩu mạnh hơn và khác nhau cho mỗi instance
      MSSQL_PID: 'Developer'
    ports:
      - "1403:1433" # Map cổng 1403 của host vào cổng 1433 của container sql_reference
    volumes:
      - sql_reference_data:/var/opt/mssql
    networks:
      - citizen_network
    restart: unless-stopped

# Định nghĩa các named volumes để lưu trữ dữ liệu bền vững
volumes:
  sql_bca_data:
    driver: local
  sql_btp_data:
    driver: local
  sql_reference_data: # Volume mới cho DB_Reference
    driver: local

# Định nghĩa network tùy chỉnh để các container có thể giao tiếp nếu cần
networks:
  citizen_network:
    driver: bridge